import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import matter from 'gray-matter';
import { Marked } from 'marked';
import { createHighlighter } from 'shiki';
import {
  slugify,
  isPublished,
  byDateDesc,
  assertEntry,
  normalizeDate,
  addHeadingIds,
  buildRssXml,
  buildSitemapXml,
} from './lib/content.mjs';

const SITE_URL = 'https://ravianand1988.github.io';
const SITE_TITLE = 'Ravi Anand Kumar';
const SITE_DESCRIPTION =
  'Writing about frontend architecture, migrations, design systems and AI-assisted engineering.';

const GENERATED_DIR = join('src', 'generated');
const PUBLIC_DIR = join(GENERATED_DIR, 'public');

const highlighter = await createHighlighter({
  themes: ['github-light', 'github-dark'],
  langs: ['typescript', 'javascript', 'html', 'scss', 'bash', 'json', 'sql', 'csharp'],
});

const marked = new Marked({
  gfm: true,
  renderer: {
    code({ text, lang }) {
      const language = highlighter.getLoadedLanguages().includes(lang) ? lang : 'text';
      return highlighter.codeToHtml(text, {
        lang: language,
        themes: { light: 'github-light', dark: 'github-dark' },
      });
    },
  },
});

async function readCollection(dir) {
  let files;
  try {
    files = await readdir(dir);
  } catch {
    return [];
  }

  const entries = [];
  for (const file of files.filter((f) => f.endsWith('.md'))) {
    const sourcePath = join(dir, file);
    const raw = await readFile(sourcePath, 'utf8');
    const { data, content } = matter(raw);

    // Normalize before validating: frontmatter dates reach us as Date objects,
    // and assertEntry checks the ISO string form.
    const entry = { ...data, date: normalizeDate(data.date) };

    if (!isPublished(entry)) continue;
    assertEntry(entry, sourcePath);

    // Headings carry ids so the rail's on-this-page list has something to link
    // to, and so a heading can be deep-linked at all.
    const { html, headings } = addHeadingIds(await marked.parse(content));

    entries.push({
      slug: entry.slug ? slugify(entry.slug) : slugify(file.replace(/\.md$/, '')),
      title: entry.title,
      description: entry.description,
      date: entry.date,
      pillar: entry.pillar,
      html,
      headings,
    });
  }

  return entries.sort(byDateDesc);
}

function toTs(name, entries) {
  return `export const ${name}: GeneratedEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
}

const posts = await readCollection(join('content', 'writing'));
const projects = await readCollection(join('content', 'projects'));

await rm(GENERATED_DIR, { recursive: true, force: true });
await mkdir(PUBLIC_DIR, { recursive: true });

await writeFile(
  join(GENERATED_DIR, 'content.ts'),
  `// GENERATED by tools/build-content.mjs. Do not edit; do not commit.
export interface GeneratedHeading {
  id: string;
  text: string;
  level: number;
}

export interface GeneratedEntry {
  slug: string;
  title: string;
  description: string;
  date: string;
  pillar: string;
  html: string;
  headings: GeneratedHeading[];
}

${toTs('posts', posts)}
${toTs('projects', projects)}`,
);

await writeFile(
  join(GENERATED_DIR, 'slugs.ts'),
  `// GENERATED by tools/build-content.mjs. Do not edit; do not commit.
export const writingSlugs: string[] = ${JSON.stringify(posts.map((p) => p.slug))};
export const projectSlugs: string[] = ${JSON.stringify(projects.map((p) => p.slug))};
`,
);

await writeFile(
  join(GENERATED_DIR, 'slugs.json'),
  JSON.stringify(
    { writingSlugs: posts.map((p) => p.slug), projectSlugs: projects.map((p) => p.slug) },
    null,
    2,
  ),
);

await writeFile(
  join(PUBLIC_DIR, 'rss.xml'),
  buildRssXml({
    siteUrl: SITE_URL,
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    items: posts.map((p) => ({
      title: p.title,
      description: p.description,
      path: `/writing/${p.slug}`,
      date: p.date,
    })),
  }),
);

await writeFile(
  join(PUBLIC_DIR, 'sitemap.xml'),
  buildSitemapXml({
    siteUrl: SITE_URL,
    paths: [
      '/',
      '/writing',
      '/projects',
      '/ai',
      '/about',
      ...posts.map((p) => `/writing/${p.slug}`),
      ...projects.map((p) => `/projects/${p.slug}`),
    ],
  }),
);

console.log(`build-content: ${posts.length} posts, ${projects.length} projects`);
